# Generated by Django 5.1.6 on 2025-02-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='room',
            new_name='roomno',
        ),
    ]
